/*
 * Pipeline Lengthwise Stress Viewer
 */
package ru.gss.plsviewer.chart;

import javax.swing.text.DefaultFormatterFactory;
import org.jdesktop.application.Action;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.plot.PolarPlot;
import ru.gss.plsviewer.commons.DlgDirEdit;
import ru.gss.plsviewer.commons.NoLocaleNumberFormatter;

/**
 * Dialog for edit of chart parameters.
 * @version 1.1.0 10.12.2020
 * @author Sergey Guskov
 */
public class DlgParameterPolarChartEdit extends DlgDirEdit < JFreeChart > {

    /**
     * Constructor.
     */
    public DlgParameterPolarChartEdit() {
        super();
        initComponents();
        jftfX1.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfX2.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfX3.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
    }

    /**
     * Setter editing object.
     * @param aTempObj editing object
     */
    @Override
    public void setTempObj(final JFreeChart aTempObj) {
        putTempObj(aTempObj);
        PolarPlot plot = (PolarPlot) getTempObj().getPlot();
        jftfX1.setValue(plot.getAxis().getRange().getLowerBound());
        jftfX2.setValue(plot.getAxis().getRange().getUpperBound());
        jftfX3.setValue(((NumberAxis) plot.getAxis()).getTickUnit().getSize());
        jchbX1.setSelected(plot.getAxis().isAutoRange());
        jchbX3.setSelected(plot.getAxis().isAutoTickUnitSelection());
        getRootPane().setDefaultButton(jbtnOk);
    }

    /**
     * Init new object.
     * @return new object
     */
    @Override
    public JFreeChart createTempObj() {
        return null;
    }

    /**
     * Action for Cancel button.
     */
    @Action
    public void acCancel() {
        setChangeObj(false);
    }

    /**
     * Action for OK button.
     */
    @Action
    public void acOk() {
        if (checkFormattedTextFieldNullNoSupposed(jftfX1, -100000.0, 100000.0)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfX2, -100000.0, 100000.0)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfX3, 0.0, 100000.0)) {
            return;
        }
        PolarPlot plot = (PolarPlot) getTempObj().getPlot();
        plot.getAxis().setRange(getDoubleFromFormattedTextField(jftfX1), getDoubleFromFormattedTextField(jftfX2));
        ((NumberAxis) plot.getAxis()).setTickUnit(new NumberTickUnit(getDoubleFromFormattedTextField(jftfX3)));
        plot.getAxis().setAutoRange(jchbX1.isSelected());
        plot.getAxis().setAutoTickUnitSelection(jchbX3.isSelected());
        setChangeObj(true);
    }

    //CHECKSTYLE:OFF
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnOk = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlbX1 = new javax.swing.JLabel();
        jftfX1 = new javax.swing.JFormattedTextField();
        jftfX2 = new javax.swing.JFormattedTextField();
        jftfX3 = new javax.swing.JFormattedTextField();
        jlbX3 = new javax.swing.JLabel();
        jchbX3 = new javax.swing.JCheckBox();
        jchbX1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ru.gss.plsviewer.PLSViewerApp.class).getContext().getResourceMap(DlgParameterPolarChartEdit.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ru.gss.plsviewer.PLSViewerApp.class).getContext().getActionMap(DlgParameterPolarChartEdit.class, this);
        jbtnOk.setAction(actionMap.get("acOk")); // NOI18N
        jbtnOk.setName("jbtnOk"); // NOI18N

        jbtnCancel.setAction(actionMap.get("acCancel")); // NOI18N
        jbtnCancel.setName("jbtnCancel"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jlbX1.setText(resourceMap.getString("jlbX1.text")); // NOI18N
        jlbX1.setName("jlbX1"); // NOI18N

        jftfX1.setName("jftfX1"); // NOI18N
        jftfX1.setPreferredSize(new java.awt.Dimension(50, 20));

        jftfX2.setName("jftfX2"); // NOI18N
        jftfX2.setPreferredSize(new java.awt.Dimension(50, 20));

        jftfX3.setName("jftfX3"); // NOI18N
        jftfX3.setPreferredSize(new java.awt.Dimension(50, 20));

        jlbX3.setText(resourceMap.getString("jlbX3.text")); // NOI18N
        jlbX3.setName("jlbX3"); // NOI18N

        jchbX3.setText(resourceMap.getString("jchbX3.text")); // NOI18N
        jchbX3.setName("jchbX3"); // NOI18N

        jchbX1.setText(resourceMap.getString("jchbX1.text")); // NOI18N
        jchbX1.setName("jchbX1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbX1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchbX1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbX3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jchbX3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jftfX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftfX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jftfX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbX1)
                    .addComponent(jftfX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchbX1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbX3)
                    .addComponent(jchbX3)
                    .addComponent(jftfX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOk)
                    .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnOk;
    private javax.swing.JCheckBox jchbX1;
    private javax.swing.JCheckBox jchbX3;
    private javax.swing.JFormattedTextField jftfX1;
    private javax.swing.JFormattedTextField jftfX2;
    private javax.swing.JFormattedTextField jftfX3;
    private javax.swing.JLabel jlbX1;
    private javax.swing.JLabel jlbX3;
    // End of variables declaration//GEN-END:variables
    //CHECKSTYLE:ON
}
